export const caseFieldDefaults = {
  listingOrder: '1', personName: '', age: '31', occupation: '', city: '', goal: '', portrait: '', portraitAlt: '',
  fd: { enabled: true, principal: '200000', rate: '6.5', years: '3', frequency: '4' },
  sip: { enabled: true, monthly: '10000', rate: '10', years: '15', initial: '0' },
};

const story = (slug, title, excerpt, name, age, occupation, city, goal, fd, sip, html) => ({
  id: slug, slug, path: `/case-studies/${slug}/`, title, excerpt, html,
  image: `/case-studies/${name.toLowerCase()}-${city.toLowerCase()}.webp`, imageAlt: `Generated portrait illustrating ${name}, a fictional ${age}-year-old ${occupation.toLowerCase()} in ${city}`,
  profile: { name, age, occupation, city, goal }, examples: { fd, sip },
  seo: { title: `${title} | Finbharat`, description: excerpt },
});

export const defaultCaseStudies = [
  story('srijan-financial-independence', 'Srijan, 31. A future with more choice.',
    'A tech professional in Hyderabad explores how FDs for nearer needs and mutual funds for a longer horizon could fit his financial independence goal.',
    'Srijan', 31, 'Tech professional', 'Hyderabad', 'Financial independence',
    { principal: 200000, rate: 6.5, years: 3, frequency: 4 }, { monthly: 10000, rate: 10, years: 15, initial: 0 },
    `<h2>Building a career. Making room for life.</h2><p>In this illustrative story, Srijan is a 31-year-old tech professional living in Hyderabad. Work keeps him busy, and his salary gives him a regular starting point. He wants to build savings that could give him more choice in the years ahead: time for family, a career change, or a slower pace.</p><p>He starts with what he can understand today: monthly spending, commitments, money already saved and the amount he could comfortably set aside. Financial independence is his ambition, rather than a promised retirement date.</p>
    <h2>Give each part of the plan a timeline.</h2><h3>An FD for a nearer need</h3><p>Srijan explores a ₹2,00,000 fixed deposit over three years at an assumed annual rate of 6.5%, compounded quarterly. A defined maturity date helps him think about when he may need this money. Before considering an actual deposit, he would compare the institution’s rate, payout arrangements and early withdrawal terms.</p><p>His emergency money needs its own access plan. A locked deposit is not automatically the same as money available immediately and without a cost.</p><h3>A SIP for a longer horizon</h3><p>For his longer-term goal, he models ₹10,000 a month over 15 years using a 10% annual return assumption. He uses this illustration to understand the contribution required and the effect of time, rather than to choose a specific mutual fund.</p><p>A SIP is a contribution method. It does not guarantee a return or remove market risk. The value of a mutual fund investment can fall; fund type, suitability, costs and taxes all matter.</p>
    <h2>Financial independence is a conversation about expenses, too.</h2><p>A future investment value alone does not tell Srijan when he can stop working. He also needs to consider inflation, dependants, housing, healthcare and how much uncertainty he can accept. Lower-return scenarios and changing expenses deserve a place in the plan.</p><ul><li>Separate near-term needs from longer-term ambitions.</li><li>Keep an accessible reserve for unexpected expenses.</li><li>Review contributions when income or commitments change.</li><li>Discuss investment suitability with an appropriately qualified adviser.</li></ul>
    <h2>Start with the numbers. Keep asking better questions.</h2><p>The FD and SIP examples below use the same formulas as Finbharat’s calculators. Sample rates are assumptions, not offers or forecasts. Srijan is a fictional persona; no investment or achieved financial outcome is claimed.</p>`),
  story('meera-personal-family-goals', 'Meera, 42. For her family. And herself.',
    'A homemaker in Chennai brings everyday savings, family priorities and personal ambitions into one clearer planning conversation.',
    'Meera', 42, 'Homemaker', 'Chennai', 'Personal and family goals',
    { principal: 100000, rate: 6, years: 2, frequency: 4 }, { monthly: 3000, rate: 8, years: 10, initial: 0 },
    `<h2>The person behind everyday decisions.</h2><p>Meera is a fictional 42-year-old homemaker in Chennai. She keeps track of household priorities, but wants the same clarity about savings and longer-term decisions. Her questions include family goals and ambitions of her own.</p><p>She begins by bringing the available savings, regular commitments and account access into one conversation. Understanding the plan should belong to every decision-maker in the family.</p><h2>Some money has a nearer purpose.</h2><p>Meera explores a ₹1,00,000 FD for two years at an assumed annual rate of 6%, compounded quarterly. This lets her examine a defined timeline for a nearer expense. She would check the actual institution’s terms, interest payout and early withdrawal conditions before deciding.</p><h2>Other goals have more time.</h2><p>For a longer horizon, she models ₹3,000 a month over ten years using an 8% annual return assumption. She can use the SIP calculator to try smaller contributions or different return assumptions and understand the difference.</p><p>The example does not select a mutual fund, assess suitability or establish that a goal is funded. Actual returns fluctuate, may be negative, and are affected by costs and taxes. Family goals such as education also need their own future-cost estimate after inflation.</p><h2>A plan she can participate in.</h2><ul><li>Write down personal goals alongside family priorities.</li><li>Check who owns and can access the savings.</li><li>Understand nomination arrangements and account documents.</li><li>Revisit timelines and affordability when circumstances change.</li></ul><p>The goal calculator is a way to explore time, inflation and existing savings separately. It gives Meera a starting point for questions, while her decisions remain her own.</p><h2>Clear assumptions. Space to decide.</h2><p>This is an illustrative planning story, not a customer experience or a financial recommendation. The examples below show sample calculations only; no outcome is claimed for Meera.</p>`),
  story('arjun-variable-income', 'Arjun, 42. Every trip. A little more possibility.',
    'An auto driver in Bengaluru explores savings for quieter days and small regular contributions toward a longer-term goal.',
    'Arjun', 42, 'Auto driver', 'Bengaluru', 'Planning with variable income',
    { principal: 50000, rate: 6, years: 1, frequency: 4 }, { monthly: 2000, rate: 8, years: 10, initial: 0 },
    `<h2>A working day does not always earn the same amount.</h2><p>In this fictional story, Arjun is a 42-year-old auto driver in Bengaluru. Earnings change with the number of trips and days worked, while fuel, vehicle maintenance and household commitments still need to be covered.</p><p>He first looks at what remains after those costs. Before choosing an investment amount, he wants an access plan for quieter days, repairs and unexpected expenses.</p><h2>Understand when saved money can be used.</h2><p>Arjun explores a ₹50,000 fixed deposit over one year at an assumed 6% annual rate, compounded quarterly. The illustration helps him see the deposit and estimated interest separately. An actual decision would depend on the institution’s terms and his ability to leave that money deposited.</p><p>He would check early withdrawal rules rather than assume a deposit is available immediately without a cost. His day-to-day buffer and a defined-tenure deposit can have different jobs.</p><h2>Small contributions need to fit real cash flow.</h2><p>For a longer-term goal, he models ₹2,000 a month over ten years using an 8% annual return assumption. The example assumes the same contribution every month; it does not model changing earnings, missed contributions or actual market movements.</p><p>He can try a smaller amount in the calculator and think about what remains affordable in a quieter month. A SIP does not guarantee returns, and a mutual fund’s value can fall. Risk, suitability and costs need to be understood before investing.</p><ul><li>Account for fuel, maintenance and essential spending first.</li><li>Keep a practical access plan for interruptions to earnings.</li><li>Try contribution amounts that fit quieter months too.</li><li>Review the plan when work or family commitments change.</li></ul><h2>One useful conversation at a time.</h2><p>Arjun’s story illustrates a possible planning conversation, not his actual investments or results. The sample calculations below exclude taxes, fees, inflation and early withdrawals. They are not proof that a future goal is funded.</p>`),
].map((item, index) => ({ ...item, order: index + 1 }));

export function caseSeedFields(item) {
  const strings = values => Object.fromEntries(Object.entries(values).map(([key, value]) => [key, String(value)]));
  return { listingOrder: String(item.order), personName: item.profile.name, age: String(item.profile.age), occupation: item.profile.occupation, city: item.profile.city, goal: item.profile.goal, portrait: item.image, portraitAlt: item.imageAlt,
    fd: { enabled: Boolean(item.examples.fd), ...strings(item.examples.fd || {}) }, sip: { enabled: Boolean(item.examples.sip), ...strings(item.examples.sip || {}) } };
}
