export const faqs = [
  ['What is Finbharat?', 'Finbharat is building thoughtful technology for a more understandable and inclusive financial future for people across India. Its direction centres on clarity, trust and supporting people in making their own decisions.'],
  ['Who is Finbharat built for?', 'Finbharat is being designed for people across regions, languages, income levels, abilities and levels of digital confidence. That includes first-time and experienced investors, and people who have been excluded from complex financial systems.'],
  ['How do the calculators work?', 'The calculators run entirely in your browser using standard compound-interest and investment formulas. You choose the amount, time and rate assumptions. The FD calculator estimates maturity, the SIP calculator models regular contributions, and the goal calculator accounts for inflation and current savings.'],
  ['How does Finbharat use AI?', 'Finbharat’s AI direction is to make information clearer and more accessible while supporting human decisions. Clarity, privacy, language access and transparency about limitations guide this direction. Specific capabilities and availability have not been confirmed here.'],
  ['Are calculator results guaranteed?', 'No. Calculator results are illustrative estimates based on the assumptions you enter. Actual returns, rates, taxes and outcomes may vary. They are not financial advice.'],
  ['Where can I download the Finbharat app?', 'Verified Google Play and Apple App Store links have not yet been supplied. The download section shows clearly marked placeholders until official links and app availability are confirmed.'],
  ['How does Finbharat think about inclusion?', 'Inclusion means designing around real lives: different languages and regions, different incomes, different access needs and different levels of digital confidence. Finbharat aims to support understanding, agency and choice without pressure.'],
];
export const pillars = [
  { title: 'Clarity', headline: 'Understanding is a powerful first step.', body: 'Plain language. Visible assumptions. Space to ask questions. Financial information should help you understand what a choice means for your life.', art: 'pathways', caption: 'A clearer path forward', alt: 'Risograph illustration of an ivory path winding through layered teal hills towards a sun' },
  { title: 'Access', headline: 'More ways to feel included.', body: 'Different languages, abilities and levels of digital confidence deserve thoughtful design. Access begins when we listen to the many ways people navigate everyday life.', art: 'community', caption: 'A wider circle', alt: 'Risograph artwork of overlapping teal and lavender circles forming a connected community' },
  { title: 'Confidence', headline: 'A little understanding goes a long way.', body: 'Explore assumptions, try a different number and see what changes. Confidence grows through understanding, at your pace and on your terms.', art: 'milestones', caption: 'Room to grow', alt: 'Risograph artwork of layered steps and a lavender sun representing goals and milestones' },
  { title: 'Choice', headline: 'Your life. Your decisions.', body: 'Useful technology creates room to consider your options. Our direction is to support your agency with clear information, without urgency or pressure.', art: 'pathways', caption: 'More than one way forward', alt: 'A winding financial pathway in a warm ivory and teal risograph landscape' },
  { title: 'Opportunity', headline: 'The future should have room for everyone.', body: 'A more understandable financial world can widen the circle. We are building with people who have too often been left out of the conversation in mind.', art: 'community', caption: 'Possibilities, connected', alt: 'Interconnected circles in teal, mint and lavender printed with halftone texture' },
];
